version: 0.2

phases:
    config:
        commands:
            - pip install -r requirements.txt
    build:
        commands:
            - aws s3 cp stacks/ s3://$SOURCE_BUCKET/stacks --recursive
            - python3 deploy.py