version: 0.2

phases:
    install:
        commands:
            - pip install -r requirements.txt
    build:
        commands:
            - aws s3 cp stacks/ s3://$SOURCE_BUCKET/stacks --recursive
            - export template_path=$(pwd)/stacks/
            - python3 deploy.py